import { apiFetch, apiJson } from './config';

// ── Agent API helpers ─────────────────────────────────────────

/**
 * List files generated by the agent for a given session.
 * @param {string} sessionId - Chat session ID
 * @returns {Promise<{files: Array}>}
 */
export async function listGeneratedFiles(sessionId) {
  return apiJson(`/agent/files?session_id=${encodeURIComponent(sessionId)}`);
}

/**
 * Get a signed download URL for a generated file.
 * Fetches a short-lived file token first, then builds the full URL.
 * @param {string} fileUrl - Relative URL from the file list (e.g. /agent/download/uid/sid/file.csv)
 * @returns {Promise<string>} Full URL with token query param
 */
export async function getDownloadUrl(fileUrl) {
  const tokenRes = await apiFetch('/auth/file-token');
  const { token } = await tokenRes.json();
  const base = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
  const separator = fileUrl.includes('?') ? '&' : '?';
  return `${base}${fileUrl}${separator}token=${encodeURIComponent(token)}`;
}

/**
 * Download a generated file (triggers browser download).
 * @param {string} fileUrl - Relative URL from the file list
 * @param {string} filename - Suggested filename for save dialog
 */
export async function downloadGeneratedFile(fileUrl, filename) {
  const url = await getDownloadUrl(fileUrl);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || '';
  document.body.appendChild(a);
  a.click();
  a.remove();
}
